### ISSUE TITLE
Sugerencia de uso de patrón Iterator

### ISSUE THREAD

**Issue by omcoello** [galleta/-Java-_Productor_Consumidor#2]
Hola! Para manejar el valor de un contenedor con varios subcontenedores sería bueno con el uso de un iterador para así poder recorrerlos de manera recursiva y poder calcular el valor total del contenedor  eficientemente sin necesidad de realizar  for anidados.

**Comment by galleta** [comment]
Ajam, se muy bien lo que es un iterador, ajam ajam, eficiencia, ajam ajam
