### ISSUE TITLE
Identificación del CodeSmell Dead Code

### ISSUE THREAD

**Issue by omcoello** [galleta/-Java-_Productor_Consumidor#4]
Se encontró un parámetro que es obsoleto para el funcionamiento del método put de la clase Productor por lo que se utilizó la técnica de refactorización de Remove Parameter para así evitar utilizar un parámetro innecesario en un método y a su vez se apuntó correctamente el valor del parámetro al atributo de manera directa.

**Comment by galleta** [comment]
Que listo pareces poniendo cosas en inglés en vez de decir que quieres quitar un parámetro, haz tú el código y lo quitas xD
