### ISSUE TITLE
Identificación del CodeSmell Data Clump

### ISSUE THREAD

**Issue by omcoello** [galleta/-Java-_Productor_Consumidor#5]
Se utilizan campos de datos en común entre las clases Productor y Consumidor por lo que sería viable utilizar la técnica de refactorización de Extract Class para así poder extraer los datos en común y poder generalizarlos sin que esto afecte el funcionamiento del programa

**Comment by galleta** [comment]
Ajam ajam, Extract Class, generator, ajam ajam, learn how to programming, ajam ajam
